version: 2

defaults: &defaults
  working_directory: ~/org
  # Available images https://hub.docker.com/r/circleci/node/tags/
  docker:
    - image: circleci/node:10.14.0-browsers

aliases:
  - &restore_yarn_cache
    name: Restore yarn cache
    keys:
      - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-packages-{{ .Branch }}
      - yarn-packages-
  - &save_yarn_cache
    name: Save yarn cache
    paths:
      - ~/.cache/yarn
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
  - &filter_master
    branches:
      only: master
  - &attach
    at: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - run: yarn install --frozen-lockfile
      - save_cache: *save_yarn_cache

      - store_artifacts:
          path: package.json

      - persist_to_workspace:
          root: ~/org
          paths:
            - .
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Build
          command: yarn run build

      - run:
          name: Lint
          command: yarn run lint

      - run:
          name: Unit tests
          command: |
            npx aw -c aw.config.js --mocha.bail false --mocha.reporter mocha-junit-reporter --mocha.reporterOptions.mochaFile ./coverage/junit/junit.xml
            if [ ! -z "$COVERALLS_REPO_TOKEN" ]; then
              echo "Uploading coverage results to coveralls.io..."
              cat ./coverage/unit/lcov.info | npx coveralls
            fi

      - run:
          name: Integration tests
          command: |
            DocId=$(curl -s --data-binary @data/apps/org-chart-test.qvf http://localhost:9076/v1/apps/import | jq -r '.attributes.id')
            APP_ID=$DocId yarn run test:integration --chrome.browserWSEndpoint "ws://localhost:3000" --no-launch

      - store_artifacts:
          path: ./test/integration/__artifacts__

      - store_test_results:
          path: coverage/junit

      - save_cache: *save_yarn_cache

  publish-dev:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/org
      - store_artifacts:
          path: ./dist

workflows:
  version: 2
  build-all:
    jobs:
      - install
      - build:
          requires:
            - install
      - publish-dev:
          requires:
            - build
          #filters:
          # branches:
          #  only:
          #   - master
